# -*- coding: utf-8 -*-
# Deployment settings for SlidingHomeC.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.4/s3e/makefile_builder/mkb.py', 'c:/Users/User/Desktop/SlidingHome/SlidingHomeC.mkb', '--buildenv=VC11', '--fake-vc-call', '--deploy-only']
mkb = 'c:/Users/User/Desktop/SlidingHome/SlidingHomeC.mkb'
mkf = ['c:\\marmalade\\7.4\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.4\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.4\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.4\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.4\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.4\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.4\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.4\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\marmalade\\7.4\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.4\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'c:\\marmalade\\7.4\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'c:\\marmalade\\7.4\\modules\\iwtween\\iwtween.mkf', 'c:\\users\\user\\desktop\\slidinghome\\modules\\soundengine\\soundengine.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/User/Desktop/SlidingHome/data', '.', 0),
    ('c:/Users/User/Desktop/SlidingHome/data/audio', 'audio', 0),
    ('c:/Users/User/Desktop/SlidingHome/data/textures', 'textures', 0),
    ('c:/Users/User/Desktop/SlidingHome/data/fonts', 'fonts', 0),
    ('c:/Users/User/Desktop/SlidingHome/data-ram/data-gles1,c:/Users/User/Desktop/SlidingHome/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'SlidingHomeC'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'SlidingHomeC'
    long_caption = 'SlidingHomeC'
    version = [0, 0, 0]
    config = ['c:/Users/User/Desktop/SlidingHome/data/app.icf']
    data_dir = 'c:/Users/User/Desktop/SlidingHome/data'
    iphone_link_lib = []
    osx_ext_dll = ['c:/marmalade/7.4/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.4/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_x86/SlidingHomeC.so',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_x86/SlidingHomeC.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_x86_tizen/SlidingHomeC.s86',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_x86_tizen/SlidingHomeC.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_firefoxos/SlidingHomeC.js',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_firefoxos/SlidingHomeC.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_mips/SlidingHomeC.so',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_mips/SlidingHomeC.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_arm/SlidingHomeC.s3e',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_arm/SlidingHomeC.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_mips/SlidingHomeC.so',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_mips/SlidingHomeC.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_gcc_x86_android/SlidingHomeC.so',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_gcc_x86_android/SlidingHomeC.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_arm/SlidingHomeC.s3e',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_arm/SlidingHomeC.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Debug_SlidingHomeC_VC11_x86/SlidingHomeC.s86',
                   'release' : r'c:/Users/User/Desktop/SlidingHome/build_slidinghomec_vc11/Release_SlidingHomeC_VC11_x86/SlidingHomeC.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
